name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: node-version:18

      - name: Test pipeline
        run: echo "CI is working"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Verify Node and npm
        run: |
          node -v
          npm -v

      - name: Install Salesforce CLI+SGD
        run: |
          npx @salesforce/cli --version
          echo "Salesforce CLI installed"
          npm install -g sfdx-git-delta

      - name: Verify org login
        run: npx @salesforce/cli org list

      - name: Authenticate to Dev2 org
        run: |
          echo "${{ secrets.DEV2_AUTH_URL }}" | tr -d '\r' > auth.txt
          npx @salesforce/cli org login sfdx-url -f auth.txt -a dev2

      - name: Debug files
        run: ls -la

      - name: Debug metadata
        run: find force-app -type f

      - name: Generate delta
        run: sfdx sgd:source:delta --to HEAD --from origin/main --output-dir delta --generate-delta

      - name: Validate Deployment
        run: npx @salesforce/cli project deploy start --manifest force-app/main/default/manifest/package.xml --target-org dev2 --check-only --wait 10

      - name: Deploy to Dev2
        run: npx @salesforce/cli project deploy start --manifest force-app/main/default/manifest/package.xml --target-org dev2 --wait 10
